syntax = "proto3";

package StarMap.Index.API;

service ModRepositoryService {
	rpc GetMods (GetModsRequest) returns (GetModsResponse);
	rpc GetModDetails (GetModDetailsRequest) returns (GetModDetailsResponse);
}

message GetModsRequest 
{
	string search = 1;
}

message GetModsResponse {
	repeated Mod mods = 1;
}

message GetModDetailsRequest {
	string id = 1;
}

message GetModDetailsResponse 
{
	ModDetails mod = 1;
}

message GetModDownloadLocationRequest
{
	string mod_id = 1;
	string version_id = 2;
}

message GetModDownloadLocationResponse
{
	string location = 1;
}

message Mod {
	string id = 1;
	string name = 2;
	string author = 4;
}

message ModDetails
{
	Mod mod = 1;
	repeated ModVersion versions = 2;
	string description = 3;
}

message ModVersion
{
	string id = 1;
	string version = 2;
	string download_location = 3;
}